import { Router } from "express";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { loadDB, saveDB } from "./db.js";
import { archiveServer, runtime, sendCommand, startServer, stopServer, killServer, serverDir } from "./manager.js";
export const pteroRouter = Router();
const db=()=>loadDB(), records=():any[]=>(db() as any).servers??[], saveRecords=(s:any[])=>{const d=db();d.servers=s;saveDB(d)}, find=(id:string)=>records().find(s=>s.id===id), admin=(r:any)=>r.user?.role==="admin", owns=(r:any,s:any)=>!!s&&(admin(r)||s.ownerId===r.user.id), deny=(res:any)=>res.status(403).json({error:"You do not have access to this server"}), uid=()=>crypto.randomUUID();
function access(req:any,res:any,next:any){const s=find(req.params.id);if(!owns(req,s))return deny(res);req.pteroServer=s;next()}
function safe(v:string){return path.basename(String(v||"")).replace(/[^a-zA-Z0-9._-]/g,"_")}
function dirFor(s:any,t:string){const d=path.join(serverDir(s.id),t);fs.mkdirSync(d,{recursive:true});return d}
function log(s:any,action:string,message:string){s.activity=[...(s.activity??[]),{id:uid(),action,message,createdAt:new Date().toISOString()}].slice(-200)}

pteroRouter.get("/servers/:id/stats",access,(req,res)=>{const s=req.pteroServer,rt=runtime(s.id);res.json({cpu:0,memory:s.memory,memoryUsed:0,disk:fs.existsSync(serverDir(s.id))?fs.statSync(serverDir(s.id)).size:0,networkRx:0,networkTx:0,uptime:rt?Math.floor((Date.now()-rt.startedAt)/1000):0,online:!!rt})});
pteroRouter.post("/servers/:id/restart",access,(req,res)=>{const s=req.pteroServer;if(s.suspended)return res.status(423).json({error:"Server is suspended"});try{stopServer(s.id);setTimeout(()=>{try{startServer(s);s.status="online";saveRecords(records())}catch{}},1500);s.status="starting";log(s,"restart","Server restart requested");saveRecords(records());res.json({ok:true})}catch(e){res.status(400).json({error:String(e)})}});

pteroRouter.get("/servers/:id/startup",access,(req:any,res:any)=>{const s=req.pteroServer,f=path.join(serverDir(s.id),"server.properties");let properties="";try{properties=fs.readFileSync(f,"utf8")}catch{}res.json({version:s.version,software:s.software,jar:"server.jar",memory:s.memory,port:s.port,command:`java -Xms128M -Xmx${s.memory}M -jar server.jar --nogui`,properties})});
pteroRouter.put("/servers/:id/startup",access,(req:any,res:any)=>{const s=req.pteroServer;if(req.body.memory!==undefined)s.memory=Math.max(512,Number(req.body.memory));if(req.body.version)s.version=String(req.body.version);if(req.body.port)s.port=Number(req.body.port);if(typeof req.body.properties==="string")fs.writeFileSync(path.join(serverDir(s.id),"server.properties"),req.body.properties);log(s,"startup","Startup configuration updated");saveRecords(records());res.json({ok:true,server:s})});

pteroRouter.get("/servers/:id/motd",access,(req:any,res:any)=>{const f=path.join(serverDir(req.pteroServer.id),"server.properties");let p="";try{p=fs.readFileSync(f,"utf8")}catch{}const m=p.match(/^motd=(.*)$/m);res.json({motd:m?.[1]??"VOID HOST"})});
pteroRouter.put("/servers/:id/motd",access,(req:any,res:any)=>{const s=req.pteroServer,f=path.join(serverDir(s.id),"server.properties");let p="";try{p=fs.readFileSync(f,"utf8")}catch{}const motd=String(req.body.motd??"VOID HOST").replace(/[\r\n]/g," ").slice(0,120);p=/^motd=.*$/m.test(p)?p.replace(/^motd=.*$/m,`motd=${motd}`):`${p}\nmotd=${motd}\n`;fs.writeFileSync(f,p);log(s,"motd","Server MOTD updated");saveRecords(records());res.json({ok:true,motd})});

pteroRouter.get("/servers/:id/network",access,(req:any,res:any)=>{const s=req.pteroServer,a=s.allocations??[{id:s.port,ip:"0.0.0.0",port:s.port,primary:true}];res.json({allocations:a,primary:a.find((x:any)=>x.primary)??a[0]})});
pteroRouter.post("/servers/:id/network",access,(req:any,res:any)=>{if(!admin(req))return res.status(403).json({error:"Admin only"});const s=req.pteroServer,port=Number(req.body.port);if(!Number.isInteger(port)||port<1024||port>65535)return res.status(400).json({error:"Invalid port"});if((s.allocations??[]).some((x:any)=>x.port===port))return res.status(409).json({error:"Port already allocated"});s.allocations=[...(s.allocations??[]),{id:port,ip:String(req.body.ip||"0.0.0.0"),port,primary:!(s.allocations??[]).length}];log(s,"allocation",`Port ${port} allocated`);saveRecords(records());res.json(s.allocations)});
pteroRouter.patch("/servers/:id/network/:port",access,(req:any,res:any)=>{if(!admin(req))return res.status(403).json({error:"Admin only"});const s=req.pteroServer,a=s.allocations??[],x=a.find((v:any)=>v.port===Number(req.params.port));if(!x)return res.status(404).json({error:"Allocation not found"});if(req.body.primary){a.forEach((v:any)=>v.primary=false);x.primary=true;s.port=x.port}saveRecords(records());res.json(a)});
pteroRouter.delete("/servers/:id/network/:port",access,(req:any,res:any)=>{if(!admin(req))return res.status(403).json({error:"Admin only"});const s=req.pteroServer,port=Number(req.params.port);s.allocations=(s.allocations??[]).filter((x:any)=>x.port!==port);if(!s.allocations.length)s.allocations=[{id:s.port,ip:"0.0.0.0",port:s.port,primary:true}];else if(!s.allocations.some((x:any)=>x.primary))s.allocations[0].primary=true;log(s,"allocation",`Port ${port} removed`);saveRecords(records());res.json({ok:true,allocations:s.allocations})});

pteroRouter.get("/servers/:id/backups",access,(req:any,res:any)=>{const d=path.join(process.cwd(),"data","backups");fs.mkdirSync(d,{recursive:true});const pre=`${req.pteroServer.id}-`;res.json(fs.readdirSync(d).filter(x=>x.startsWith(pre)).map(name=>{const st=fs.statSync(path.join(d,name));return{name,size:st.size,createdAt:st.mtime.toISOString()}}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)))});
pteroRouter.post("/servers/:id/backups",access,async(req:any,res:any)=>{const s=req.pteroServer,d=path.join(process.cwd(),"data","backups");fs.mkdirSync(d,{recursive:true});const name=`${s.id}-${Date.now()}.tar.gz`;try{await archiveServer(s.id,path.join(d,name));log(s,"backup",`Backup ${name} created`);saveRecords(records());res.status(201).json({name})}catch(e){res.status(400).json({error:String(e)})}});
pteroRouter.delete("/servers/:id/backups/:name",access,(req:any,res:any)=>{const name=safe(req.params.name),s=req.pteroServer;if(!name.startsWith(`${s.id}-`))return res.status(400).json({error:"Invalid backup"});const f=path.join(process.cwd(),"data","backups",name);if(!fs.existsSync(f))return res.status(404).json({error:"Backup not found"});fs.unlinkSync(f);log(s,"backup",`Backup ${name} deleted`);saveRecords(records());res.json({ok:true})});

pteroRouter.get("/servers/:id/managers/:type",access,(req:any,res:any)=>{if(!["plugins","mods","modpacks"].includes(req.params.type))return res.status(400).json({error:"Unknown manager"});const d=dirFor(req.pteroServer,req.params.type);res.json(fs.readdirSync(d).filter(x=>!x.startsWith(".")).map(name=>{const st=fs.statSync(path.join(d,name));return{name,size:st.size,createdAt:st.mtime.toISOString()}}))});
pteroRouter.post("/servers/:id/managers/:type",access,async(req:any,res:any)=>{const t=req.params.type,s=req.pteroServer;if(!["plugins","mods","modpacks"].includes(t))return res.status(400).json({error:"Unknown manager"});const url=String(req.body.url||"");if(!/^https:\/\//i.test(url))return res.status(400).json({error:"Only HTTPS download URLs are allowed"});try{const r=await fetch(url,{headers:{"User-Agent":"VOID-HOST/1.0"}});if(!r.ok)throw new Error(`Download failed: HTTP ${r.status}`);const u=new URL(url),name=safe(String(req.body.name||path.basename(u.pathname)||`${t}.jar`)),b=Buffer.from(await r.arrayBuffer());if(b.length<1||b.length>200*1024*1024)throw new Error("Package must be 1 byte to 200 MB");fs.writeFileSync(path.join(dirFor(s,t),name),b);log(s,t,`Installed ${name}`);saveRecords(records());res.status(201).json({name,size:b.length})}catch(e){res.status(400).json({error:String(e)})}});
pteroRouter.delete("/servers/:id/managers/:type/:name",access,(req:any,res:any)=>{const t=req.params.type,s=req.pteroServer,name=safe(req.params.name);if(!["plugins","mods","modpacks"].includes(t))return res.status(400).json({error:"Unknown manager"});const f=path.join(dirFor(s,t),name);if(!fs.existsSync(f))return res.status(404).json({error:"Package not found"});fs.unlinkSync(f);log(s,t,`Removed ${name}`);saveRecords(records());res.json({ok:true})});

pteroRouter.get("/servers/:id/schedules",access,(req:any,res:any)=>res.json(req.pteroServer.schedules??[]));
pteroRouter.post("/servers/:id/schedules",access,(req:any,res:any)=>{const s=req.pteroServer,x={id:uid(),name:String(req.body.name||"New schedule"),cron:String(req.body.cron||"0 3 * * *"),action:String(req.body.action||"command"),payload:String(req.body.payload||""),active:req.body.active!==false,lastRun:null,createdAt:new Date().toISOString()};s.schedules=[...(s.schedules??[]),x];saveRecords(records());res.json(x)});
pteroRouter.patch("/servers/:id/schedules/:schedule",access,(req:any,res:any)=>{const s=req.pteroServer,x=(s.schedules??[]).find((v:any)=>v.id===req.params.schedule);if(!x)return res.status(404).json({error:"Schedule not found"});Object.assign(x,req.body);saveRecords(records());res.json(x)});
pteroRouter.delete("/servers/:id/schedules/:schedule",access,(req:any,res:any)=>{const s=req.pteroServer;s.schedules=(s.schedules??[]).filter((x:any)=>x.id!==req.params.schedule);saveRecords(records());res.json({ok:true})});
pteroRouter.post("/servers/:id/schedules/:schedule/run",access,async(req:any,res:any)=>{const s=req.pteroServer,x=(s.schedules??[]).find((v:any)=>v.id===req.params.schedule);if(!x)return res.status(404).json({error:"Schedule not found"});try{if(x.action==="command"&&x.payload)sendCommand(s.id,x.payload);else if(x.action==="restart"){stopServer(s.id);setTimeout(()=>{try{startServer(s)}catch{}},1200)}else if(x.action==="start")startServer(s);else if(x.action==="stop")stopServer(s.id);else if(x.action==="kill")killServer(s.id);else if(x.action==="backup"){const d=path.join(process.cwd(),"data","backups");fs.mkdirSync(d,{recursive:true});await archiveServer(s.id,path.join(d,`${s.id}-${Date.now()}.tar.gz`))}x.lastRun=new Date().toISOString();saveRecords(records());res.json({ok:true})}catch(e){res.status(400).json({error:String(e)})}});

pteroRouter.get("/servers/:id/databases",access,(req:any,res:any)=>res.json(req.pteroServer.databases??[]));
pteroRouter.post("/servers/:id/databases",access,(req:any,res:any)=>{const s=req.pteroServer,x={id:uid(),name:String(req.body.name||`minecraft_${s.id.slice(0,6)}`),username:String(req.body.username||`void_${s.id.slice(0,6)}`),host:"127.0.0.1",port:3306,status:"metadata-only"};s.databases=[...(s.databases??[]),x];saveRecords(records());res.status(201).json(x)});
pteroRouter.delete("/servers/:id/databases/:database",access,(req:any,res:any)=>{const s=req.pteroServer;s.databases=(s.databases??[]).filter((x:any)=>x.id!==req.params.database);saveRecords(records());res.json({ok:true})});
pteroRouter.get("/servers/:id/users",access,(req:any,res:any)=>res.json(req.pteroServer.subusers??[]));
pteroRouter.post("/servers/:id/users",access,(req:any,res:any)=>{const s=req.pteroServer,u={id:uid(),username:String(req.body.username||""),permissions:Array.isArray(req.body.permissions)?req.body.permissions:["control.console","control.start","control.stop","file.read"],createdAt:new Date().toISOString()};if(!u.username)return res.status(400).json({error:"Username required"});s.subusers=[...(s.subusers??[]),u];saveRecords(records());res.status(201).json(u)});
pteroRouter.patch("/servers/:id/users/:user",access,(req:any,res:any)=>{const s=req.pteroServer,u=(s.subusers??[]).find((x:any)=>x.id===req.params.user);if(!u)return res.status(404).json({error:"User not found"});if(Array.isArray(req.body.permissions))u.permissions=req.body.permissions;saveRecords(records());res.json(u)});
pteroRouter.delete("/servers/:id/users/:user",access,(req:any,res:any)=>{const s=req.pteroServer;s.subusers=(s.subusers??[]).filter((x:any)=>x.id!==req.params.user);saveRecords(records());res.json({ok:true})});
pteroRouter.get("/servers/:id/activity",access,(req:any,res:any)=>res.json((req.pteroServer.activity??[]).slice(-100).reverse()));
